# Generated by Django 5.1 on 2024-09-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['created_at'], 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
    ]
